#!/usr/bin/env python3
"""Fails (exit 1) when any page's JSON-LD is broken: a block that does not parse, more than one JSON-LD block on a
page, more than one BreadcrumbList, a FAQPage whose questions differ from the visible accordion, or a Service with
no provider. Runs on pull requests (.github/workflows/jsonld.yml). go/ is skipped (generated by the Ads contractor)."""
import glob, html, json, re, sys
SKIP_DIRS = ("go/", ".git/", "node_modules/")
txt = lambda s: re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", s))).strip()
def nodes(j):
    if isinstance(j, list): return [n for x in j for n in nodes(x)]
    if isinstance(j, dict) and "@graph" in j: return j["@graph"]
    return [j] if isinstance(j, dict) else []
def ty(n):
    t = n.get("@type", []); return set(t if isinstance(t, list) else [t])
errors = []
files = [f for f in glob.glob("**/*.html", recursive=True) if not f.startswith(SKIP_DIRS)]
for f in sorted(files):
    h = open(f, encoding="utf-8").read()
    raw = re.findall(r'<script\b[^>]*\btype\s*=\s*["\']application/ld\+json["\'][^>]*>([\s\S]*?)</script>', h, re.I)
    if len(raw) > 1: errors.append(f"{f}: {len(raw)} JSON-LD blocks (expected one @graph)")
    ns = []
    for r in raw:
        try: ns += nodes(json.loads(r))
        except Exception as e: errors.append(f"{f}: JSON-LD does not parse ({e})"); continue
    if sum(1 for n in ns if "BreadcrumbList" in ty(n)) > 1: errors.append(f"{f}: more than one BreadcrumbList")
    for n in ns:
        if "Service" in ty(n) and not n.get("provider"): errors.append(f"{f}: Service without provider")
        if "FAQPage" in ty(n):
            h = re.sub(r'<p class="tx-faq-src">[\s\S]*?</p>', '', h)  # source attribution lines on faq.html are not part of the answer
            vis = {txt(q): txt(a) for q, a in re.findall(r'<button[^>]*class="faq-q[^"]*"[^>]*>([\s\S]*?)</button>\s*<div[^>]*class="faq-a[^"]*"[^>]*>([\s\S]*?)</div>', h)}
            vis.update({txt(q): txt(a) for q, a in re.findall(r"<details[^>]*>\s*<summary[^>]*>([\s\S]*?)</summary>([\s\S]*?)</details>", h)})
            for q in n.get("mainEntity", []):
                name = q.get("name"); ans = (q.get("acceptedAnswer") or {}).get("text")
                if name not in vis: errors.append(f"{f}: FAQPage question not visible on the page: {name!r}")
                elif ans != vis[name]: errors.append(f"{f}: FAQPage answer differs from the visible answer: {name!r}")
print(f"checked {len(files)} pages, {len(errors)} errors")
for e in errors: print("  " + e)
sys.exit(1 if errors else 0)
